insert into Invent (id, nombre, id_usuario) values (11111, 'Asoka', 1);
insert into Invent (id, nombre, id_usuario) values (11112, 'Fixflex', 1);
insert into Invent (id, nombre, id_usuario) values (11113, 'Sonsing', 1);
insert into Invent (id, nombre, id_usuario) values (11114, 'Pannier', 1);
insert into Invent (id, nombre, id_usuario) values (11115, 'Stringtough', 1);
insert into Invent (id, nombre, id_usuario) values (11116, 'Cardify', 1);
insert into Invent (id, nombre, id_usuario) values (11117, 'Keylex', 1);
insert into Invent (id, nombre, id_usuario) values (11118, 'Home Ing', 1);
insert into Invent (id, nombre, id_usuario) values (11119, 'Flowdesk', 1);
insert into Invent (id, nombre, id_usuario) values (111110, 'Redhold', 1);

insert into Conceptos (id, nombre, id_inv) values (1, 'Grand Cherokee', 1);
insert into Conceptos (id, nombre, id_inv) values (2, '9000', 1);
insert into Conceptos (id, nombre, id_inv) values (3, 'Country', 1);
insert into Conceptos (id, nombre, id_inv) values (4, 'Tundra', 1);
insert into Conceptos (id, nombre, id_inv) values (5, 'Eldorado', 1);
insert into Conceptos (id, nombre, id_inv) values (6, '430 Scuderia', 2);
insert into Conceptos (id, nombre, id_inv) values (7, 'Riviera', 2);
insert into Conceptos (id, nombre, id_inv) values (8, 'Protege', 2);
insert into Conceptos (id, nombre, id_inv) values (9, 'Mustang', 2);
insert into Conceptos (id, nombre, id_inv) values (10, 'LS', 2);
insert into Conceptos (id, nombre, id_inv) values (11, 'Firefly', 3);
insert into Conceptos (id, nombre, id_inv) values (12, 'Jimmy', 3);
insert into Conceptos (id, nombre, id_inv) values (13, 'Allante', 3);
insert into Conceptos (id, nombre, id_inv) values (14, 'Marauder', 3);
insert into Conceptos (id, nombre, id_inv) values (15, 'Mark LT', 3);
insert into Conceptos (id, nombre, id_inv) values (16, 'Vantage', 4);
insert into Conceptos (id, nombre, id_inv) values (17, 'Navigator', 4);
insert into Conceptos (id, nombre, id_inv) values (18, '9000', 4);
insert into Conceptos (id, nombre, id_inv) values (19, 'Insight', 4);
insert into Conceptos (id, nombre, id_inv) values (20, 'New Yorker', 4);
insert into Conceptos (id, nombre, id_inv) values (21, 'SL-Class', 5);
insert into Conceptos (id, nombre, id_inv) values (22, 'Eclipse', 5);
insert into Conceptos (id, nombre, id_inv) values (23, 'F-Series Super Duty', 5);
insert into Conceptos (id, nombre, id_inv) values (24, 'Supra', 5);
insert into Conceptos (id, nombre, id_inv) values (25, 'TL', 5);
insert into Conceptos (id, nombre, id_inv) values (26, 'Cherokee', 6);
insert into Conceptos (id, nombre, id_inv) values (27, 'MX-6', 6);
insert into Conceptos (id, nombre, id_inv) values (28, 'XC90', 6);
insert into Conceptos (id, nombre, id_inv) values (29, 'Astro', 6);
insert into Conceptos (id, nombre, id_inv) values (30, 'Accord', 6);
insert into Conceptos (id, nombre, id_inv) values (31, 'Tiburon', 7);
insert into Conceptos (id, nombre, id_inv) values (32, 'SL-Class', 7);
insert into Conceptos (id, nombre, id_inv) values (33, 'Grand Prix', 7);
insert into Conceptos (id, nombre, id_inv) values (34, 'Miata MX-5', 7);
insert into Conceptos (id, nombre, id_inv) values (35, 'Tundra', 7);
insert into Conceptos (id, nombre, id_inv) values (36, 'Trooper', 8);
insert into Conceptos (id, nombre, id_inv) values (37, 'FX', 8);
insert into Conceptos (id, nombre, id_inv) values (38, 'Vandura 3500', 8);
insert into Conceptos (id, nombre, id_inv) values (39, '9000', 8);
insert into Conceptos (id, nombre, id_inv) values (40, '240SX', 8);
insert into Conceptos (id, nombre, id_inv) values (41, 'Malibu', 9);
insert into Conceptos (id, nombre, id_inv) values (42, 'i-370', 9);
insert into Conceptos (id, nombre, id_inv) values (43, 'Sedona', 9);
insert into Conceptos (id, nombre, id_inv) values (44, 'Leone', 9);
insert into Conceptos (id, nombre, id_inv) values (45, 'Passat', 9);
insert into Conceptos (id, nombre, id_inv) values (46, 'Lancer', 10);
insert into Conceptos (id, nombre, id_inv) values (47, 'Taurus', 10);
insert into Conceptos (id, nombre, id_inv) values (48, 'Navigator', 10);
insert into Conceptos (id, nombre, id_inv) values (49, 'IS F', 10);
insert into Conceptos (id, nombre, id_inv) values (50, 'Crown Victoria', 10);

